### ISSUE TITLE
Volume Search

### ISSUE THREAD

**Issue by jimmylle** [Shadowys/btapi#10]
When i try to search using &volumeno=1 for example, it keeps volumes that contain 1s such as 11,12,13,etc.

Ex: https://baka-tsuki-api.herokuapp.com/api?title=Moonlight_Sculptor&volumeno=1
This gives me volume 1 and 10-19.

**Comment by danieltanfh95** [comment]
Fixed. 
Previous api did not match for the volume and number. Also, the search was not working on external links.
It is now fixed. Please check if the fix is completed.
