### ISSUE TITLE
http://btapi-shadowys.rhcloud.com/ API endpoint down

### ISSUE THREAD

**Issue by M4rtinK** [Shadowys/btapi#29]
The http://btapi-shadowys.rhcloud.com/ API edpoint seems to be throwing a 503:

```

Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

**Comment by danieltanfh95** [comment]
It seems that the app has stopped. I've restarted it and it's working again now.

**Comment by M4rtinK** [comment]
Yep, seems to be working fine now. Thanks! :)
