### ISSUE TITLE
application error on Heroku

### ISSUE THREAD

**Issue by Nandaka** [Shadowys/btapi#5]
Hit an error when tried to open https://baka-tsuki-api.herokuapp.com/api?type=LIGHT_NOVEL

![image](https://cloud.githubusercontent.com/assets/836867/7244490/f09a80c6-e80e-11e4-8028-976b043fccc5.png)

**Comment by Nandaka** [comment]
possibly linked to #1

**Comment by danieltanfh95** [comment]
I've switched the route to the following but have not documented it:

https://baka-tsuki-api.herokuapp.com/api/category?type=LIGHT_NOVEL
